spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ecommerce.platform: INFO
    org.springframework.web: WARN

platform:
  processing:
    delay: 2000
  retry:
    max-attempts: 3
  external-apis:
    timeout: 10000
    retry-count: 5