spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    show-actuator: true

logging:
  level:
    com.ecommerce.platform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG

platform:
  processing:
    delay: 500
  retry:
    max-attempts: 1
  external-apis:
    timeout: 5000
    retry-count: 2