CREATE TABLE IF NOT EXISTS users (
    id UUID UNIQUE PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    google_id VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON DATABASE ecommerce_dev_db TO ecommerceuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ecommerceuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ecommerceuser;